version: '3.1'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example
    volumes:
      - db_data:/var/lib/postgresql/data
  api: 
    build: .
    restart: always
    depends_on:
      - db
    ports:
      - "3002:3002"
    environment: 
      DB_PASS: example
      DB_HOST: db
      DB_USER: postgres
      DB_NAME: postgres
volumes:
  db_data:
    